apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "8080"
    prometheus.io/scrape: "true"
  labels:
    app: demo-product-svc
  name: demo-product-svc
  namespace: default
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: demo-product-svc
  sessionAffinity: None
  type: ClusterIP
