apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: prometheus-scaledobject
spec:
  scaleTargetRef:
    name: demo-product-svc
  # Interval to when to query Prometheus
  pollingInterval: 5
  # The period to wait after the last trigger reported active
  # before scaling the deployment back to 1
  cooldownPeriod: 10
  # min replicas keda will scale to
  # if you have an app that has an dependency on pubsub
  # this would be a good use case to set it to zero
  # why keep your app running if your topic has no messages?
  minReplicaCount: 1
  # max replicas keda will scale to
  maxReplicaCount: 20
  advanced:
    # HPA config
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          stabilizationWindowSeconds: 10
          policies:
            - type: Percent
              value: 5
              periodSeconds: 10
        scaleUp:
          stabilizationWindowSeconds: 0
          policies:
            - type: Percent
              value: 5
              periodSeconds: 10
  triggers:
    - type: prometheus
      metadata:
        # address where keda can reach our prometheus on
        serverAddress: http://prometheus-server.default.svc.cluster.local
        # metric on what we want to scale
        metricName: http_server_requests_seconds_count
        # if treshold is reached then Keda will scale our deployment
        threshold: "100"
        query: rate(http_server_requests_seconds_count{uri="/v1/products"}[2m])